name: Heroku Sign In Workflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  heroku_sign_in_job:
    runs-on: ubuntu-latest
    name: Heroku Sign Job 
    steps:
      - name: Checkout code to Runner
        uses: actions/checkout@v2
      - name: Sign In to Heroku 
        uses: nyakaz73/heroku-django-deploy-example@v0.1
        id: login
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }} 
          heroku_email_address: ${{ secrets.HEROKU_EMAIL_ADDRESS }} 
          working_directory: ./tests/djangoherokuapp
          heroku_app_name: django-heroku-123
      - name: Get the output status
        run: echo "${{ steps.login.outputs.status }}"
